'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';

export default function StudentsPage() {
  const [data, setData] = useState<any>({ items: [], pagination: {} }); const [q, setQ] = useState(''); const [filters, setFilters] = useState({ classId: '', batchId: '', status: '', gender: '', pageSize: '10' }); const [batches, setBatches] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  const load = async (page = 1) => { setLoading(true); try { const r = await api.get('/students', { params: { q: q || undefined, ...filters, page, pageSize: filters.pageSize } }); setData(r.data); } finally { setLoading(false); } };
  useEffect(() => { api.get('/batches').then(r => setBatches(r.data)); load(); }, []);
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Students</h1><p className="text-sm text-slate-500">Manage student accounts and profiles.</p></div><Link className="btn" href="/dashboard/students/new">Add student</Link></div>
    <div className="card"><form onSubmit={e => { e.preventDefault(); load(); }} className="grid grid-cols-1 md:grid-cols-5 gap-3"><input className="input md:col-span-2" placeholder="Search admission no., name, phone, email, class" value={q} onChange={e => setQ(e.target.value)} /><input className="input" placeholder="Class" value={filters.classId} onChange={e => setFilters({ ...filters, classId: e.target.value })} /><select className="input" value={filters.batchId} onChange={e => setFilters({ ...filters, batchId: e.target.value })}><option value="">All batches</option>{batches.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select><select className="input" value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="deleted">Deleted</option></select><select className="input" value={filters.gender} onChange={e => setFilters({ ...filters, gender: e.target.value })}><option value="">All genders</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select><select className="input" value={filters.pageSize} onChange={e => setFilters({ ...filters, pageSize: e.target.value })}><option value="10">10 / page</option><option value="25">25 / page</option><option value="50">50 / page</option><option value="100">100 / page</option></select><button className="btn">Search</button></form></div>
    <div className="card overflow-x-auto"><table className="table"><thead><tr><th>Admission</th><th>Student</th><th>Class / Batch</th><th>Phone</th><th>Status</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="text-slate-500">Loading students…</td></tr> : data.items.length === 0 ? <tr><td colSpan={6} className="text-slate-500">No students found.</td></tr> : data.items.map((s: any) => <tr key={s.id}><td>{s.admission_number}</td><td><div className="font-medium">{s.first_name} {s.last_name}</div><div className="text-xs text-slate-500">{s.email}</div></td><td>{s.class_id}{s.batch?.name && ` · ${s.batch.name}`}</td><td>{s.phone}</td><td><span className={s.status === 'active' ? 'text-green-700' : 'text-slate-500'}>{s.status}</span></td><td className="text-right"><Link className="btn-outline" href={`/dashboard/students/${s.id}`}>View</Link></td></tr>)}</tbody></table><div className="flex justify-between items-center mt-4 text-sm"><span>{data.pagination.total || 0} total</span><div className="space-x-2"><button className="btn-outline" disabled={data.pagination.page <= 1} onClick={() => load(data.pagination.page - 1)}>Previous</button><span>Page {data.pagination.page || 1} of {data.pagination.totalPages || 1}</span><button className="btn-outline" disabled={data.pagination.page >= data.pagination.totalPages} onClick={() => load(data.pagination.page + 1)}>Next</button></div></div></div>
  </div>;
}
