const fs = require("fs");
const path = require("path");

const content = [
'const nodemailer = require("nodemailer");',
'const env = require("../config/env");',
"",
"let transporter = null;",
"let etherealPreviewUrl = null;",
"let initPromise = null;",
"",
"async function initTransporter() {",
"  if (transporter) return transporter;",
"  if (initPromise) return initPromise;",
"  initPromise = (async () => {",
'    if (env.SMTP.host && env.SMTP.user) {',
"      const t = nodemailer.createTransport({",
"        host: env.SMTP.host,",
"        port: env.SMTP.port,",
"        secure: env.SMTP.port === 465,",
"        auth: { user: env.SMTP.user, pass: env.SMTP.pass },",
"      });",
"      try {",
"        await t.verify();",
"        transporter = t;",
'        console.log("[mail] SMTP connected -", env.SMTP.host + ":" + env.SMTP.port);',
"      } catch (err) {",
'        console.error("[mail] SMTP error:", err.message);',
"      }",
"    }",
"    if (!transporter) {",
"      try {",
"        const testAccount = await nodemailer.createTestAccount();",
"        transporter = nodemailer.createTransport({",
'          host: "smtp.ethereal.email",',
"          port: 587,",
"          secure: false,",
"          auth: { user: testAccount.user, pass: testAccount.pass },",
"        });",
'        etherealPreviewUrl = "https://ethereal.email/login?user=" + encodeURIComponent(testAccount.user);',
'        console.log("[mail] Ethereal active:", etherealPreviewUrl);',
'        console.log("[mail]   user:", testAccount.user, "pass:", testAccount.pass);',
"      } catch (err) {",
'        console.error("[mail] Ethereal failed:", err.message);',
"      }",
"    }",
"    return transporter;",
"  })();",
"  return initPromise;",
"}",
"",
"async function sendMail(opts) {",
"  const t = await initTransporter();",
'  if (!t) { console.log("[mail:unavailable]", opts.to); return { skipped: true }; }',
"  const info = await t.sendMail({",
'    from: env.SMTP.from || \'"Dwaraka Academy" <no-reply@dwaraka.local>\',',
"    to: opts.to,",
"    subject: opts.subject,",
"    text: opts.text,",
"    html: opts.html || opts.text,",
"  });",
"  const pu = nodemailer.getTestMessageUrl(info);",
'  if (pu) { console.log("[mail:sent]", opts.to, "-", opts.subject); console.log("[mail:preview]", pu); }',
'  else { console.log("[mail:sent]", opts.to, "-", opts.subject); }',
"  return info;",
"}",
"",
'function esc(s) { return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;"); }',
"",
"function base(body) {",
'  return \'<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><style>\' +',
'    "body{margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,\\\'Segoe UI\\\',sans-serif;background:#f3f4f6}" +',
'    ".wrapper{padding:32px 16px}.container{max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08)}" +',
'    ".header{background:linear-gradient(135deg,#6D28D9,#8B5CF6);padding:32px 40px 24px;text-align:center}" +',
'    ".header h1{color:#fff;margin:0;font-size:22px;font-weight:700}.header p{color:rgba(255,255,255,0.8);margin:6px 0 0;font-size:13px}" +',
'    ".body{padding:32px 40px;color:#1f2937}.body h2{font-size:18px;font-weight:600;margin:0 0 12px}.body p{font-size:14px;line-height:1.6;margin:0 0 16px;color:#4b5563}" +',
'    ".credential-box{background:#f9fafb;border:1px solid #e5e7eb;border-radius:10px;padding:16px 20px;margin:16px 0}" +',
'    ".credential-box .label{font-size:11px;text-transform:uppercase;letter-spacing:0.5px;color:#9ca3af}" +',
'    ".credential-box .value{font-size:15px;font-weight:600;color:#111827;margin-bottom:10px;font-family:\\\'Courier New\\\',monospace;word-break:break-all}" +',
'    ".credential-box .value:last-child{margin-bottom:0}" +',
'    ".btn{display:inline-block;background:linear-gradient(135deg,#6D28D9,#8B5CF6);color:#fff;text-decoration:none;padding:10px 24px;border-radius:8px;font-weight:600;font-size:13px}" +',
'    ".footer{padding:20px 40px;background:#f9fafb;text-align:center}.footer p{font-size:12px;color:#9ca3af;margin:0}" +',
'    "</style></head><body><div class=\\\'wrapper\\\'><div class=\\\'container\\\'>" +',
"    '<div class=\\'header\\'><h1>&#x1f3eb; Dwaraka Academy</h1><p>Excellence in Education Since 2020</p></div>' +",
"    '<div class=\\'body\\'>' + body + '</div>' +",
"    '<div class=\\'footer\\'><p>Dwaraka Academy - Excellence in Education Since 2020</p><p style=\\'margin-top:6px\\'>This is an automated message.</p></div>' +",
"    \"</div></div></body></html>\";",
"}",
"",
"function welcomeEmail(o) {",
"  const rl = o.role.charAt(0).toUpperCase() + o.role.slice(1);",
"  const uh = (o.username && o.username !== o.email)",
"    ? '<div class=\\'label\\'>Admission No</div><div class=\\'value\\'>' + esc(o.username) + '</div>' : '';",
"  const bh =",
"    '<h2>Welcome to Dwaraka Academy</h2><p>Hello <strong>' + esc(o.name) + '</strong>,</p>' +",
"    \"<p>A \" + rl + \" account has been created for you.</p>\" +",
"    '<div class=\\'credential-box\\'><div class=\\'label\\'>Email</div><div class=\\'value\\'>' + esc(o.email) + '</div>' + uh +",
"    '<div class=\\'label\\'>Temporary Password</div><div class=\\'value\\'>' + esc(o.tempPassword) + '</div></div>' +",
'    "<p style=\\\'color:#ef4444;font-size:13px;font-weight:500;\\\'>Change your password on first login.</p>" +',
"    '<p style=\\'text-align:center;margin-top:20px;\\'><a class=\\'btn\\' href=\\'' + (env.CORS_ORIGIN || 'http://localhost:3000') + '/login\\'>Sign In</a></p>';",
"  return {",
"    subject: o.subject || 'Your ' + rl + ' Account - Dwaraka Academy',",
"    html: base(bh),",
"    text: 'Welcome ' + o.name + '!\\\\n\\\\nA ' + rl + ' account has been created.\\\\n\\\\nEmail: ' + o.email + '\\\\n' + (o.username && o.username !== o.email ? 'Username: ' + o.username + '\\\\n' : '') + 'Temporary password: ' + o.tempPassword + '\\\\n\\\\nLog in and change your password.'",
"  };",
"}",
"",
"function resetPasswordEmail(o) {",
"  const rl = o.role ? o.role.charAt(0).toUpperCase() + o.role.slice(1) + ' ' : '';",
"  const bh =",
"    '<h2>Password Reset</h2><p>Hello <strong>' + esc(o.name) + '</strong>,</p>' +",
"    '<p>Your ' + rl + 'password has been reset.</p>' +",
"    '<div class=\\'credential-box\\'><div class=\\'label\\'>Email</div><div class=\\'value\\'>' + esc(o.email) + '</div>' +",
"    '<div class=\\'label\\'>Temporary Password</div><div class=\\'value\\'>' + esc(o.tempPassword) + '</div></div>' +",
'    "<p style=\\\'color:#ef4444;font-size:13px;font-weight:500;\\\'>Set a new password on your next login.</p>" +',
"    '<p style=\\'text-align:center;margin-top:20px;\\'><a class=\\'btn\\' href=\\'' + (env.CORS_ORIGIN || 'http://localhost:3000') + '/login\\'>Sign In</a></p>';",
"  return {",
"    subject: 'Password Reset - Dwaraka Academy',",
"    html: base(bh),",
"    text: 'Hello ' + o.name + ',\\\\n\\\\nYour password has been reset.\\\\n\\\\nEmail: ' + o.email + '\\\\nTemporary password: ' + o.tempPassword + '\\\\n\\\\nLog in and change your password.'",
"  };",
"}",
"",
"function parentApprovalEmail(o) {",
"  const bh =",
"    '<h2>Parent Account Approved</h2><p>Hello <strong>' + esc(o.parentName) + '</strong>,</p>' +",
"    '<p>Your parent account for <strong>' + esc(o.studentName) + '</strong> has been approved.</p>' +",
"    \"<p>Monitor attendance, marks, assignments, and fee status.</p>\" +",
"    '<div class=\\'credential-box\\'><div class=\\'label\\'>Email</div><div class=\\'value\\'>' + esc(o.email) + '</div>' +",
"    '<div class=\\'label\\'>Temporary Password</div><div class=\\'value\\'>' + esc(o.tempPassword) + '</div></div>' +",
'    "<p style=\\\'color:#ef4444;font-size:13px;font-weight:500;\\\'>Change your password on first login.</p>" +',
"    '<p style=\\'text-align:center;margin-top:20px;\\'><a class=\\'btn\\' href=\\'' + (env.CORS_ORIGIN || 'http://localhost:3000') + '/login\\'>Sign In</a></p>';",
"  return {",
"    subject: 'Parent Account Approved - Dwaraka Academy',",
"    html: base(bh),",
"    text: 'Hello ' + o.parentName + ',\\\\n\\\\nYour parent account for ' + o.studentName + ' has been approved.\\\\n\\\\nEmail: ' + o.email + '\\\\nTemporary password: ' + o.tempPassword + '\\\\n\\\\nLog in and change your password.'",
"  };",
"}",
"",
"function passwordChangedEmail(o) {",
"  const bh =",
"    '<h2>Password Changed</h2><p>Hello <strong>' + esc(o.name) + '</strong>,</p>' +",
"    '<p>Your password was changed successfully.</p><p>If you did not make this change, contact the academy immediately.</p>' +",
"    '<p style=\\'text-align:center;margin-top:20px;\\'><a class=\\'btn\\' href=\\'' + (env.CORS_ORIGIN || 'http://localhost:3000') + '/login\\'>Go to Portal</a></p>';",
"  return {",
"    subject: 'Password Changed - Dwaraka Academy',",
"    html: base(bh),",
"    text: 'Hello ' + o.name + ',\\\\n\\\\nYour Dwaraka Academy password was changed successfully.\\\\n\\\\nIf you did not make this change, contact the academy immediately.'",
"  };",
"}",
"",
"module.exports = {",
"  sendMail: sendMail,",
"  initTransporter: initTransporter,",
"  welcomeEmail: welcomeEmail,",
"  resetPasswordEmail: resetPasswordEmail,",
"  parentApprovalEmail: parentApprovalEmail,",
"  passwordChangedEmail: passwordChangedEmail,",
"  getEtherealPreviewUrl: function() { return etherealPreviewUrl; }",
"};",
].join("\n");

const target = path.resolve(__dirname, "..", "utils", "mailer.js");
fs.writeFileSync(target, content, "utf8");
console.log("Written", content.length, "bytes to", target);

// Verify
delete require.cache[target];
try {
  const m = require(target);
  console.log("Exports:", Object.keys(m).join(", "));
} catch(e) {
  console.error("Load error:", e.message);
}
