'use client';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { api } from '@/lib/api';
import StudentForm from '@/components/StudentForm';

export default function StudentDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [student, setStudent] = useState<any>(null); const [batches, setBatches] = useState<any[]>([]); const [editing, setEditing] = useState(false); const [confirmingDelete, setConfirmingDelete] = useState(false); const [message, setMessage] = useState('');
  const load = () => api.get(`/students/${id}`).then(r => setStudent(r.data));
  useEffect(() => { load(); api.get('/batches').then(r => setBatches(r.data)); }, [id]);
  if (!student) return <div className="p-6 text-slate-500">Loading student…</div>;
  const action = async (url: string, body?: any) => { const r = await api.post(url, body); if (r.data.student) setStudent(r.data.student); return r.data; };
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{student.first_name} {student.last_name}</h1><p className="text-sm text-slate-500">Admission no. {student.admission_number} · {student.status}</p></div><div className="flex gap-2"><button className="btn-outline" onClick={() => setEditing(!editing)}>{editing ? 'Cancel edit' : 'Edit student'}</button><button className="btn-outline" onClick={async () => { const r = await action(`/students/${id}/reset-password`); setMessage(`New temporary password: ${r.temporaryPassword}`); }}>Reset password</button><button className="btn-outline" onClick={() => action(`/students/${id}/status`, { status: student.status === 'active' ? 'inactive' : 'active' })}>{student.status === 'active' ? 'Deactivate' : 'Activate'}</button><button className="btn-outline text-red-700" onClick={() => setConfirmingDelete(true)}>Delete</button></div></div>{message && <div className="card text-green-700">{message}</div>}
    {confirmingDelete && <div className="fixed inset-0 z-20 flex items-center justify-center bg-slate-900/40 p-4"><div className="card max-w-md"><h2 className="font-semibold">Delete student?</h2><p className="mt-2 text-sm text-slate-600">This will deactivate the login and soft-delete the student profile. The record can still be retained for audit purposes.</p><div className="mt-5 flex justify-end gap-2"><button className="btn-outline" onClick={() => setConfirmingDelete(false)}>Cancel</button><button className="btn bg-red-700 hover:bg-red-800" onClick={async () => { await api.delete(`/students/${id}`); router.push('/dashboard/students'); }}>Delete student</button></div></div></div>}
    {editing ? <StudentForm student={student} batches={batches} onSaved={saved => { setStudent(saved); setEditing(false); setMessage('Student details updated.'); }} /> : <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><section className="card"><h2 className="font-semibold mb-4">Personal details</h2><dl className="space-y-2 text-sm"><div><dt className="text-slate-500">Date of birth</dt><dd>{student.dob}</dd></div><div><dt className="text-slate-500">Gender</dt><dd>{student.gender}</dd></div><div><dt className="text-slate-500">Blood group</dt><dd>{student.blood_group || '—'}</dd></div></dl></section><section className="card"><h2 className="font-semibold mb-4">Academic details</h2><dl className="space-y-2 text-sm"><div><dt className="text-slate-500">Class</dt><dd>{student.class_id}</dd></div><div><dt className="text-slate-500">Batch</dt><dd>{student.batch?.name || 'Not assigned'}</dd></div><div><dt className="text-slate-500">Roll number</dt><dd>{student.roll_number || '—'}</dd></div></dl></section><section className="card"><h2 className="font-semibold mb-4">Contact and parent details</h2><dl className="space-y-2 text-sm"><div><dt className="text-slate-500">Email</dt><dd>{student.email}</dd></div><div><dt className="text-slate-500">Phone</dt><dd>{student.phone}</dd></div><div><dt className="text-slate-500">Parent phone</dt><dd>{student.parent_phone || '—'}</dd></div></dl></section><section className="card"><h2 className="font-semibold mb-4">Address</h2><p className="text-sm whitespace-pre-wrap">{[student.address, student.city, student.state, student.country, student.pincode].filter(Boolean).join(', ') || '—'}</p></section></div>}
  </div>;
}
